### ISSUE TITLE
CamFlow vagrant

### ISSUE THREAD

**Issue by tfjmp** [arthurscchan/ProvMark#9]
There is Vagrant file available for CamFlow, please see here: https://github.com/CamFlow/vagrant

If you want to try out yourself, I would build from this one: https://github.com/CamFlow/vagrant/blob/master/rpm/Vagrantfile

I am happy to add one for ProvMark once I understand how it is supposed to work.

**Comment by jamescheney** [comment]
Is there a particular reason to enable the GUI?  I tend to prefer to do things via vagrant ssh.

**Comment by jamescheney** [comment]
I'm also getting this error (repeatedly): 

```
default: [MIRROR] kernel-4.13.4camflow0.3.7-1.x86_64.rpm: Curl error (28): Timeout was reached for https://packagecloud-oss.global.ssl.fastly.net/4667/5014/fedora/26/package_files/270774.rpm?t=1511547811_854819ae832df7e5c8da3459cbe3aa779365ae1d [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
```

**Comment by tfjmp** [comment]
No you can turn the GUI off.

I will have a look to check if package cloud is done. Alternatively you can
use basic-fedora, it build from source.

**Comment by jamescheney** [comment]
I tried again and it seems to have managed - so probably just network randomness.

**Comment by jamescheney** [comment]
It looks like I need to keep the GUI enabled so that I can select the right kernel - it would be nice avoid this but not a big deal.

I also needed to instal json_merger and glibc-static (the latter might be the reason you've been getting mysterious errors, it seems that static libc libraries are not installed by default in this vm.  This gets me to a point where some graphs are being recorded and generalized but something goes wrong at the comparison stage.  Nevertheless by following the same steps hopefully you can also see some intermediate output in working/.

I'll add a copy of this vagrantfile and a script with the two commands.

**Comment by arthurscchan** [comment]
For the two dependencies mentioned by James. I have some additional remark. For the json_merger module of python, I have stated that at the README.md before. But for the libc static library, I have tried out in multiple linux version, it appears some of the ditribution don't event have the libc.a installed by default. It maybe also a dependency. But I doubt that without the libc.a exist, the execution of camflow will still fail no matter if it is related to how ProvMark is working.  That is, I assume if I can run CamFlow successfully on its own, then libc.a should already installed in the system. I think this may not be the dependency of ProvMark itself indeed.

**Comment by jamescheney** [comment]
I think it's possible to runCamFlow without the static libc.a installed, since that is what happens in the CamFlow/rpm Vagrantfile.  In any case, I think we can close this issue since the vagrantfile for CamFlow more-or-less seems to work.
